//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOOK
    {
        public int BOO_REC_ID { get; set; }
        public int BOO_CLI_ID { get; set; }
        public bool BOO_VALID { get; set; }
        public Nullable<System.DateTime> BOO_UPDATE_AT { get; set; }
        public string BOO_UPDATE_BY { get; set; }
    
        public virtual C_CLIENT C_CLIENT { get; set; }
        public virtual C_RECEPTION C_RECEPTION { get; set; }
    }
}
