//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CHOOSE
    {
        public int CHO_CLI_ID { get; set; }
        public int CHO_DIS_ID { get; set; }
        public int CHO_REC_ID { get; set; }
        public Nullable<System.DateTime> CHO_UPDATE_AT { get; set; }
        public string CHO_UPDATE_BY { get; set; }
    
        public virtual C_CLIENT C_CLIENT { get; set; }
        public virtual C_DISH C_DISH { get; set; }
        public virtual C_RECEPTION C_RECEPTION { get; set; }
    }
}
