//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_CLIENT()
        {
            this.C_BOOK = new HashSet<C_BOOK>();
            this.C_CHOOSE = new HashSet<C_CHOOSE>();
            this.C_FEEL_CLI_CLI = new HashSet<C_FEEL_CLI_CLI>();
            this.C_FEEL_CLI_CLI1 = new HashSet<C_FEEL_CLI_CLI>();
            this.C_FEEL_CLI_DIS = new HashSet<C_FEEL_CLI_DIS>();
            this.C_SIT = new HashSet<C_SIT>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_ACRONYM { get; set; }
        public string CLI_PASSWORD { get; set; }
        public string CLI_GROUP { get; set; }
        public string CLI_FNAME { get; set; }
        public string CLI_LNAME { get; set; }
        public string CLI_SEX { get; set; }
        public System.DateTime CLI_BDAY { get; set; }
        public string CLI_JOB { get; set; }
        public Nullable<System.DateTime> CLI_UPDATE_AT { get; set; }
        public string CLI_UPDATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BOOK> C_BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CHOOSE> C_CHOOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_FEEL_CLI_CLI> C_FEEL_CLI_CLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_FEEL_CLI_CLI> C_FEEL_CLI_CLI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_FEEL_CLI_DIS> C_FEEL_CLI_DIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SIT> C_SIT { get; set; }
    }
}
