//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DISH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_DISH()
        {
            this.C_CHOOSE = new HashSet<C_CHOOSE>();
            this.C_FEEL_CLI_DIS = new HashSet<C_FEEL_CLI_DIS>();
            this.C_OFFER = new HashSet<C_OFFER>();
        }
    
        public int DIS_ID { get; set; }
        public string DIS_NAME { get; set; }
        public int DIS_TYPE { get; set; }
        public Nullable<System.DateTime> DIS_UPDATE_AT { get; set; }
        public string DIS_UPDATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CHOOSE> C_CHOOSE { get; set; }
        public virtual C_DISHTYPE C_DISHTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_FEEL_CLI_DIS> C_FEEL_CLI_DIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_OFFER> C_OFFER { get; set; }
    }
}
