//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FEEL_CLI_DIS
    {
        public int FCD_CLI_ID { get; set; }
        public int FCD_DIS_ID { get; set; }
        public int FCD_FTY_ID { get; set; }
        public Nullable<System.DateTime> FCD_UPDATE_AT { get; set; }
        public string FCD_UPDATE_BY { get; set; }
    
        public virtual C_CLIENT C_CLIENT { get; set; }
        public virtual C_DISH C_DISH { get; set; }
        public virtual C_FEELINGTYPE C_FEELINGTYPE { get; set; }
    }
}
