//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OFFER
    {
        public int OFF_REC_ID { get; set; }
        public int OFF_DIS_ID { get; set; }
        public Nullable<System.DateTime> OFF_UPDATE_AT { get; set; }
        public string OFF_UPDATE_BY { get; set; }
    
        public virtual C_DISH C_DISH { get; set; }
        public virtual C_RECEPTION C_RECEPTION { get; set; }
    }
}
