//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RECEPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_RECEPTION()
        {
            this.C_BOOK = new HashSet<C_BOOK>();
            this.C_CHOOSE = new HashSet<C_CHOOSE>();
            this.C_OFFER = new HashSet<C_OFFER>();
            this.C_TABLE = new HashSet<C_TABLE>();
        }
    
        public int REC_ID { get; set; }
        public string REC_NAME { get; set; }
        public System.DateTime REC_DATE { get; set; }
        public System.DateTime REC_DATE_CLOSING_REG { get; set; }
        public int REC_CAPACITY { get; set; }
        public int REC_SEAT_TABLE { get; set; }
        public bool REC_VALID { get; set; }
        public Nullable<System.DateTime> REC_UPDATE_AT { get; set; }
        public string REC_UPDATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_BOOK> C_BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_CHOOSE> C_CHOOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_OFFER> C_OFFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_TABLE> C_TABLE { get; set; }
    }
}
