//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_TABLE()
        {
            this.C_SIT = new HashSet<C_SIT>();
        }
    
        public int TAB_ID { get; set; }
        public int TAB_NUMBER { get; set; }
        public int TAB_SEATING { get; set; }
        public int TAB_REC_ID { get; set; }
        public bool TAB_VALID { get; set; }
        public Nullable<System.DateTime> TAB_UPDATE_AT { get; set; }
        public string TAB_UPDATE_BY { get; set; }
    
        public virtual C_RECEPTION C_RECEPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SIT> C_SIT { get; set; }
    }
}
