//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishStatistic
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Offered { get; set; }
        public Nullable<int> Chosen { get; set; }
        public Nullable<int> Liked { get; set; }
        public Nullable<int> Disliked { get; set; }
        public int DishId { get; set; }
        public int DishTypeId { get; set; }
    }
}
